Gm 46
davidOrtiz09/GreenMarket-G2 pull request #30
Opened 2017-11-21 04:48 UTC by juanca0517

Ver detalles de mis perdidos

2017-11-25 02:28 UTC, davidOrtiz09 approved these changes
Solo un pequeño comentario, de resto me parece que esta bien.

2017-11-25 02:28 UTC, davidOrtiz09 commented on Administrador/templates/Administrador/Informes/mejoresProductos.html
> +                    <table id="detallePedidoTable" class="table dataTable" cellspacing="2"
Deberías cambiarle ese id ya que estas hablando productos y no de pedidos

2017-11-25 03:41 UTC, juantangarife requested changes

2017-11-25 03:41 UTC, juantangarife commented on Cliente/views.py
> +        detalle_mi_pedido = PedidoProducto.objects.filter(fk_pedido=id_pedido)
Cuidado, estas filtrando mal (o al menos eso creo por el nombre de las variables). Si vas a filtrar por ids tienes que hacer fk_pedido_id=id_pedido

Si quieres filtrar por instancia, en este caso tendrías que hacer fk_pedido=pedido

2017-11-26 08:08 UTC, alfyes commented on Cliente/views.py
> +        detalle_mi_pedido = PedidoProducto.objects.filter(fk_pedido=id_pedido)
De acuerdo con camilo.

2017-11-26 08:11 UTC, alfyes requested changes
Debe realizar el cambió que le comentó camilo.  Por lo demás ok.

2017-11-29 04:45 UTC, juanca0517 commented on Administrador/templates/Administrador/Informes/mejoresProductos.html
> +                    <table id="detallePedidoTable" class="table dataTable" cellspacing="2"
Hola @davidOrtiz09 , en la tabla si se muestran los productos, pero mira que estos corresponden al detalle de un pedido, por ello lo nombre de esta forma.

2017-11-30 05:05 UTC, davidOrtiz09 approved these changes
Tienes 2 conflictos de merge que debes resolver primero

2017-12-01 04:20 UTC, merged