Gm-41   Agregar favoritos
davidOrtiz09/GreenMarket-G2 pull request #35
Opened 2017-11-27 05:01 UTC by alfyes

Ya esta lista esta funcionalidad. La someto a  la revisión de ustedes.  Si todo bien soluciono el conflicto y hago el merge.

2017-11-27 05:24 UTC, alfyes commented
Ya solucione el conflicto.  Solo queda pendiente la revisión.

2017-11-28 04:02 UTC, juantangarife requested changes
Solo cambia el filtro de get_len por el "|length" nativo de Django

2017-11-28 04:02 UTC, juantangarife commented on Cliente/templatetags/app_filters.py
>  def get_len(list):
Esto no es necesario. Hay un pipe nativo que retorna la longitud de un arreglo en los templates https://docs.djangoproject.com/en/1.11/ref/templates/builtins/#length

2017-11-29 03:32 UTC, alfyes commented on Cliente/templatetags/app_filters.py
>  def get_len(list):
ok lo cambiare  aunque eso estaba en otra funcionalidad anterior. =)

2017-11-29 03:34 UTC, alfyes commented on Cliente/templatetags/app_filters.py
>  def get_len(list):
Gracias por la info, probare.

2017-11-30 04:26 UTC, merged