Gm 43
davidOrtiz09/GreenMarket-G2 pull request #37
Opened 2017-11-30 05:38 UTC by juanca0517

Buenos días, me permito subir el desarrollo de la HU GM-43 Ver mejores productores.

2017-11-30 16:59 UTC, davidOrtiz09 requested changes
Algunas sugerencias. También ten en cuenta los merge conflicts que tienes que resolver primero

2017-11-30 16:59 UTC, davidOrtiz09 commented on Administrador/utils.py
> +        promedio = 0.0
Creo que esta variable `promedio` la podrías declarar afuera del if, así no la tendrías que declarar 2 veces

2017-11-30 16:59 UTC, davidOrtiz09 commented on Cliente/templates/Cliente/calificar-mis-pedidos.html
> +                                    <option value="1">1 Uno</option>
Creo que deberías dejar solo el numero en formato numero `1` o solo en formato escrito`uno` . Pero los 2 queda algo feo . El value si estoy de acuerdo

2017-11-30 16:59 UTC, davidOrtiz09 commented on Cliente/templates/Cliente/calificar-mis-pedidos.html
> +                                <input type="submit" class="btn btn-primary" value="Guardar Calificacion"/>
te falta una tilde en `Calificación`

2017-11-30 16:59 UTC, davidOrtiz09 commented on Cliente/templates/Cliente/detalle-mis-pedidos.html
> +                                    <th class="text-center">Categoria</th>
Creo que también deberías revisar la ortografía en esta columna

2017-12-01 01:16 UTC, juanca0517 commented on Cliente/templates/Cliente/detalle-mis-pedidos.html
> +                                    <th class="text-center">Categoria</th>
Corregido, se reviso la ortografía

2017-12-01 01:16 UTC, juanca0517 commented on Cliente/templates/Cliente/calificar-mis-pedidos.html
> +                                <input type="submit" class="btn btn-primary" value="Guardar Calificacion"/>
Corregido, se reviso la ortografía

2017-12-01 01:16 UTC, juanca0517 commented on Cliente/templates/Cliente/calificar-mis-pedidos.html
> +                                    <option value="1">1 Uno</option>
Corregido, queda en formato (uno)

2017-12-01 01:16 UTC, juanca0517 commented on Administrador/utils.py
> +        promedio = 0.0
Corregido

2017-12-01 01:17 UTC, juantangarife requested changes
En general esta bien, solo hay unas cosas por ajustar. A lo único que le deberías poner cuidado es a la expresión regular de las urls porque tienen muchos parametros seguidos sin nada que los separe

2017-12-01 01:17 UTC, juantangarife commented on Cliente/templates/Cliente/detalle-mis-pedidos.html
> +                                <th colspan="8" bgcolor="#228b22" class="text-white text-center">Detelle Pedido</th>
Dice "Detelle" y no "Detalle"

2017-12-01 01:17 UTC, juantangarife commented on Cliente/urls.py
> +    url(r'^guardar-calificacion-mis-pedidos/(?P<pedido_producto>\d+)(?P<productor>\d+)(?P<id_pedido>\d+)$', views.InsertCalificacionProductoVew.as_view(), name='guardar-calificacion-mis-pedidos'),
Me preocupa que en las urls hay varios parámetros, pero no hay ningun caracter que los separe (por ejemplo un guión), y como todos son numeros, esto podría generar errores

2017-12-01 04:17 UTC, merged