Gm-205 Catalogo por Cooperativas.
davidOrtiz09/GreenMarket-G2 pull request #38
Opened 2017-12-01 19:32 UTC by alfyes

Se realizaron todas la modificaciones necesarias para soportar catálogos por cooperativas,.

Se agregó un filtro general de Cooperativas en el administrador  y  se aplicó este en todas las funcionalidades  del administrador.

También se corrigen algunos problemas encontrados durante las pruebas que realizaba. Cona gregar producto a un carrito, filtros del catálogo en la vista del cliente, cantidades disponibles en el catálogo en vista cliente y algo en la realización de la compra,

2017-12-01 19:48 UTC, davidOrtiz09 approved these changes
Yo lo veo bien y al parecer no tiene merge conflicts. :D

2017-12-02 03:36 UTC, juantangarife requested changes
En general creo que esta bien, pero tienes que crear un método que recibe el request y obtenga la cooperativa de la sesión y ese método lo reemplazas en donde tienes identificadores quemados

Por otro lado, quiero que revisemos juntos el Index dle cliente porque yo lo había simplificado, con lo que tengo entendido y depronto habían cosas que si eran necesarias.

(Los comentarios que hice fueron basados en lo que entiendo del proyecto, depronto estuve equivocado en varios comentarios, pero la idea igual es aclarar)

2017-12-02 03:36 UTC, juantangarife commented on Cliente/views.py
> +        cooperativa = cooperativas.first()
¿Por qué obtiene la primera cooperativa y no la que esta en la variable de sesión?

2017-12-02 03:36 UTC, juantangarife commented on Cliente/utils.py
> +    product = Catalogo_Producto.objects.get(fk_producto_id=product_id,fk_catalogo__fk_cooperativa_id = 1,
Aqui el id de la cooperativa esta quemado en 1

2017-12-02 03:36 UTC, juantangarife commented on Cliente/views.py
> +            'solo_favoritos': False
Yo había eliminado esto de solo_favoritos cuando hice un merge porque pensaba que ya no era necesario. ¿Me podrías aclarar para que se utiliza?

2017-12-02 03:36 UTC, juantangarife commented on Cliente/views.py
>      def post(self, request):
Creo que con lo que hice de vue este post ya no era necesario hacerlo tan complejo. Es más, yo veo que sirve para ordenar los productos y eso lo podríamos lograr con Vue de una manera más sencilla; de manera que aqui solo serviría para cambiar la cooperativa (Al menos esto es lo que yo tengo entendido

2017-12-02 03:36 UTC, juantangarife commented on Cliente/views.py
> +                                                              fk_catalogo__fk_cooperativa_id=1,
El id de la categoria esta quemado

2017-12-02 03:36 UTC, juantangarife commented on MarketPlace/utils.py
> +def cantidad_disponible_producto_catalogo(producto_catalogo, cooperativa_id):
Ahorita vi que se invocaba este método y el parametro de cooperativa_id estaba quemado en 1

2017-12-02 05:46 UTC, merged